<?php
/**
 * Implements hook_ckeditor_plugin().
 *
 * @return type
 */
function ckeditor_anchor_links_ckeditor_plugins() {
    $plugins['ckeditor_anchor_links'] = array(
        'path' => backdrop_get_path('module', 'ckeditor_anchor_links') . '/plugins/ckeditor_anchor_links',
        'file' => 'plugin.js',
        'internal' => FALSE,
        'buttons' => array(
            'Anchor' => array(
                'label' => t('Anchor Link'),
                'image' => base_path() . backdrop_get_path('module', 'ckeditor_anchor_links') . '/plugins/ckeditor_anchor_links/icons/ckeditor_anchor_links.png',
                'image_alternative' =>'{insert anchor_link}',
            ),
        ),
    );
//    echo '<pre>';
//    print_r($plugins); die;
    return $plugins;
}